# Formerly called: anthropic_filemap.yaml
# This template is heavily inspired by anthropic's computer use demo, but you can use
# it with any LM.
agent:
  templates:
    system_template: |-
      You are a helpful assistant that can interact with a computer to solve tasks.
    instance_template: |-
      <uploaded_files>
      {{working_dir}}
      </uploaded_files>
      I've uploaded a python code repository in the directory {{working_dir}}. Consider the following PR description:

      <pr_description>
      {{problem_statement}}
      </pr_description>

      Can you help me implement the necessary changes to the repository so that the requirements specified in the <pr_description> are met?
      I've already taken care of all changes to any of the test files described in the <pr_description>. This means you DON'T have to modify the testing logic or any of the tests in any way!
      Your task is to make the minimal changes to non-tests files in the {{working_dir}} directory to ensure the <pr_description> is satisfied.
      Follow these steps to resolve the issue:
      1. As a first step, it might be a good idea to find and read code relevant to the <pr_description>
      2. Create a script to reproduce the error and execute it with `python <filename.py>` using the bash tool, to confirm the error
      3. Edit the sourcecode of the repo to resolve the issue
      4. Rerun your reproduce script and confirm that the error is fixed!
      5. Think about edgecases and make sure your fix handles them as well
      Your thinking should be thorough and so it's fine if it's very long.
    action_taken_prompt_template: |-
      Latest observation:
      {{obs}}

      Your current task: {{task_name}}

      Your previously proposed subtasks:
      {{remaining_subtask_str}}

      You can refine the subtasks based on the latest observation, empty list if you think your current task is done, further decompose the first subtask by not calling any tool, and/or make tool calls to make progress.
    down_prompt_template: |-
      OK.

      Your current task: {{task_name}}

      You can decompose the task if it is too complex, empty list if you think your current task is done, further decompose the subtask by not calling any tool, and/or make tool calls to make progress.
    up_prompt_template: |-
      You have determined that the task {{done_task_name}} has been completed.

      Now, you return to the parent task.
      Your current task: {{previous_stage_task_name}}

      Your previous think: {{previous_stage_think}}

      Your remaining subtasks:
      {{remaining_subtask_str}}

      You can refine the subtasks based on the latest observation, empty list if you think your current task is done, further decompose the first subtask by not calling any tool, and/or make tool calls to make progress.
    # nonleaf_judge_done_prompt_template: |-
    #   You have successfully completed the task: {{done_task_name}}

    #   Now, you return to the parent task.
    #   Your current task: {{previous_stage_task_name}}

    #   Your previous think: {{previous_stage_think}}

    #   There are no remaining subtasks for the current task. Please determine whether the task has been completed. If it has, set the subtasks to an empty list; if not, generate the necessary subtasks required to complete the current task.
    # leaf_judge_done_prompt_template: |-
    #   You have successfully completed the task: {{done_task_name}}

    #   {{obs}}

    #   Now, you return to the parent task.
    #   Your current task: {{previous_stage_task_name}}

    #   Your previous think: {{previous_stage_think}}

    #   There are no remaining subtasks for the current task. Please determine whether the task has been completed. If it has, set the subtasks to an empty list; if not, generate the necessary subtasks required to complete the current task.
    # leaf_up_fail_prompt_template: |-
    #   You fail to complete the task: {{fail_task_name}}
    #   Because the task name is not included in the valid actions provided in the observation. Your assumptions may not be valid.
    #   Potential cause of the problem might be:
    #   1. The action name is not the EXACT match of the valid action name.
    #   2. You can't place an object directly on a Station when it's occupied by another object. Otherwise you will stack on it.
    #   3. You can't cut an object that is stacked on another object. It must be directly on the board. You should remove the object underneath first.
    #   4. You can't pick up an item that is being stacked under another item. It must be on the top.

    #   {{obs}}

    #   Now, you return to the parent task.
    #   Your current task: {{previous_stage_task_name}}

    #   Your previous think: {{previous_stage_think}}

    #   Your remaining subtasks:
    #   {{remaining_subtask_str}}

    #   We wish you to modify your subtasks in order to fix the error.
    # nonleaf_up_prompt_template: |-
    #   You have successfully completed the task: {{done_task_name}}

    #   Now, you return to the parent task.
    #   Your current task: {{previous_stage_task_name}}

    #   Your previous think: {{previous_stage_think}}

    #   Your remaining subtasks:
    #   {{remaining_subtask_str}}

    #   We wish you to refine your list of subtasks based on the latest observation to achieve your goal. Do not generate any subtasks beyond the scope of the current task.
  tools:
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: 'off'
      TQDM_DISABLE: '1'
      GIT_PAGER: cat
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/review_on_submit_m
    registry_variables:
      USE_FILEMAP: 'true'
      SUBMIT_REVIEW_MESSAGES:
        - |
          Thank you for your work on this issue. Please carefully follow the steps below to help review your changes.

          1. If you made any changes to your code after running the reproduction script, please run the reproduction script again.
            If the reproduction script is failing, please revisit your changes and make sure they are correct.
            If you have already removed your reproduction script, please ignore this step.
          2. Remove your reproduction script (if you haven't done so already).
          3. If you have modified any TEST files, please revert them to the state they had before you started fixing the issue.
            You can do this with `git checkout -- /path/to/test/file.py`. Use below <diff> to find the files you need to revert.
          4. Run the submit command again to confirm.

          Here is a list of all of your changes:

          <diff>
          {{diff}}
          </diff>
    enable_bash_tool: true
    parse_function:
      type: function_calling
  history_processors:
    - type: cache_control
      last_n_messages: 2
